### ISSUE TITLE
Segmentation tool generating completely blacked-out images

### ISSUE THREAD

**Issue by DarkestQuasar** [HakaiInstitute/hakai-segmentation#20]
I have been attempting to use the hakai-segmentation tool to detect kelp in some orthomosaic images.
The tool has been running successfully, with this prompt after calling:

```
(env1) chet@RUSSELLCWW:/mnt/c/Users/chet.russell/Documents/imagery_project$ kom find-kelp PointRetreat59202220220613.tiff result.tif
/home/chet/miniconda3/envs/env1/lib/python3.9/site-packages/rasterio/__init__.py:220: NotGeoreferencedWarning: Dataset has no geotransform, gcps, or rpcs. The identity matrix be returned.
  s = DatasetReader(path, driver=driver, sharing=sharing, **kwargs)
/home/chet/miniconda3/envs/env1/lib/python3.9/site-packages/rasterio/__init__.py:230: NotGeoreferencedWarning: The given matrix is equal to Affine.identity or its flipped counterpart. GDAL may ignore this matrix and save no geotransform without raising an error. This behavior is somewhat driver-specific.
  s = writer(path, mode, driver=driver,
/home/chet/miniconda3/envs/env1/lib/python3.9/site-packages/hakai_segmentation/managers.py:92: UserWarning: Define the correct nodata value on the input raster to speed up processing.
  warnings.warn("Define the correct nodata value on the input raster to speed up processing.", UserWarning)
Processing:   9%|███████████████
```

It then completes the generation and leaves a completely black .tif image.
I have also attempted to process a .jpg image to a .jpg and .jpg to a .tif. Both of these had the same result.
Any idea of why this is happening?

**Comment by tayden** [comment]
Hmm. Perhaps the resolution is really different? I believe that all of our imagery had a resolution of, or finer than, 10cm/pixel.

Are you able to share the image with me to investigate?

**Comment by DarkestQuasar** [comment]
Yep, no problem. I zipped the image and attached it.
I don't believe that the resolution is anywhere near 10cm/pixel, so that may be the issue.
[PointRetreat59202220220613.zip](https://github.com/HakaiInstitute/hakai-segmentation/files/9067618/PointRetreat59202220220613.zip)
.

**Comment by tayden** [comment]
I think that's likely the issue. You could try to up-sample the image to 10cm and try again, and `kom` may be able to produce something from that. That way, at least the same extents would at least be getting fed to the classifier, although with significantly less detail

**Comment by DarkestQuasar** [comment]
@tayden So I have been working on creating some more orthomosaic images with a resolution of 3cm/pixel, and processing them on a better machine. This time, the tool has been creating raster data perfectly. Thanks for the help!

**Comment by tayden** [comment]
Excellent, I'm glad it's working for you!
